--** occam-pi/Plumbing interface to the 
-- Modern Device PIR
-- @module mdpir

#IF NOT (DEFINED (MDPIR.MODULE))
#DEFINE MDPIR.MODULE
#INCLUDE "plumbing.module"

-- This module is rather application/sensor specific.
-- It may be easily generalized into a "generic PIR"
-- interface, but that is not the project for today.

PROC pir (VAL INT power.pin, sense.pin, CHAN SIGNAL motion!)
  SEQ
    serial.write.string (TX0, "Powering down.*n")
    digital.mode (power.pin, OUTPUT)
    digital.write (power.pin, LOW)
    delay (2000)
    -- serial.write.string (TX0, "Powering up.*n")
    digital.write (power.pin, HIGH)
    -- serial.write.string (TX0, "Stabilizing.*n")
    delay (6000)
    -- serial.write.string (TX0, "Sensing.*n")
    CHAN LEVEL pir:
    PAR
      digital.input (sense.pin, pir!)
      level.to.signal (pir?, motion!)
:

#ENDIF
