--** occam-pi/Plumbing interface to the 
-- Modern Device PIR
-- @module mdpir

#IF NOT (DEFINED (MDPIR.MODULE))
#DEFINE MDPIR.MODULE
#INCLUDE "plumbing.module"

-- This module is rather application/sensor specific.
-- It may be easily generalized into a "generic PIR"
-- interface, but that is not the project for today.

PROC pir.init (VAL INT power.pin, sense.pin)
  SEQ 
    digital.mode (power.pin, OUTPUT)
    digital.mode (sense.pin, INPUT)
    digital.write (power.pin, HIGH)
    delay(5000)
:

PROC pir (VAL INT sense.pin, CHAN SIGNAL motion!)
  SEQ
    CHAN LEVEL pir:
    PAR
      digital.input (sense.pin, pir!)
      level.to.signal (pir?, motion!)
:

#ENDIF
